### ISSUE TITLE
rocketsDB run error issues 

### ISSUE THREAD

**Issue by EasyLuck** [thustorage/pacman#2]
After building the project , I run the pem_rocksdb_bench and viper , a error happened ,
Error(</home/lucky/coding/pacman/benchmarks/other/pmem_rocksdb_bench.cpp>:61 OpenDB): open failed: IO error: mmap first size_t failed: Operation not supported.
The same situation as viper_bench.
Why that?
I'm so frustrated.

**Comment by EasyLuck** [comment]
such as viper: 
the bug location: 
------------------------------------------------------------------------
void *pmem_addr =
        mmap(nullptr, alloc_size, VIPER_MAP_PROT, VIPER_MAP_FLAGS, data_fd, 0);
------------------------------------------------------------------------
then do memcheck:
 MMAP_CHECK(pmem_addr)
however, the error happened and the message:
------------------------------------------------------------------------
Running ./viper_bench
Run on (32 X 3300.45 MHz CPU s)
CPU Caches:
  L1 Data 48 KiB (x16)
  L1 Instruction 32 KiB (x16)
  L2 Unified 1280 KiB (x16)
  L3 Unified 24576 KiB (x1)
Load Average: 3.48, 6.01, 8.53
threads of service / gc : 1 / 4
terminate called after throwing an instance of 'std::runtime_error'
  what():  Cannot mmap | Operation not supported (LINE: 1090)
------------------------------------------------------------------------

**Comment by EasyLuck** [comment]
------------------------------------------------------------------------

**Comment by starkwj** [comment]
Hi,

I believe this is because the PM path you used is not on a file system **with DAX**.
PMem-RocksDB and Viper mmap files with flags like _MAP_SHARED_VALIDATE_ and _MAP_SYNC_. These flags strictly require the file system to be with DAX.
Please checkout the configuration example: https://github.com/thustorage/pacman#system-configuration.

**Comment by EasyLuck** [comment]
sudo mount -o dax /dev/pmem0 /mnt/pmem0
The  /mnt/pmem0 path is be done by:
--------------------------
mkdir -p  /mnt/pmem0
--------------------------
yeah?

**Comment by starkwj** [comment]
> ## sudo mount -o dax /dev/pmem0 /mnt/pmem0
> The /mnt/pmem0 path is be done by:
> ## mkdir -p /mnt/pmem0
> yeah?

Yes.

**Comment by EasyLuck** [comment]
It can work now. Thank you.
