### ISSUE TITLE
The Opatane DCPMM Discontinued

### ISSUE THREAD

**Issue by EasyLuck** [thustorage/pacman#4]
Hi~
The intel Opatane DCPMM Discontinued. What is your option about the research on it? Can we still use the hardware to do experiments and post papers?

**Comment by starkwj** [comment]
Hi,
There are many valuable discussions on the forums such as "zhihu".
As staff from Intel said, PMem may turn into or be replaced by CXL type memory ("https://groups.google.com/g/pmem/c/EyUooHNbcjA").

**Comment by EasyLuck** [comment]
Will you continue your research based on Intel DCPMM next?
