### ISSUE TITLE
Get operations return false when LOG_BATCHING option is enabled

### ISSUE THREAD

**Issue by SeKwonLee** [thustorage/pacman#5]
Hello,

I am testing KVSs (FlatStore-H) now. But, I found get operations return false when `LOG_BATCHING` option is enabled. The tested workload is YCSB Run C (Read only) using the `eval_ycsb.sh` script.

Could you check this and let me know if I missed something?

Thanks,
Sekwon

**Comment by starkwj** [comment]
Hi Sekwon,

Sorry that the benchmark didn't drain the batching buffer and update those kv in the index after preloading. I have fixed that with https://github.com/thustorage/pacman/commit/fc5243f829c79e6e873b4bc38cf16bf51d35f73d .
Please check if this helps.

Thanks.

**Comment by SeKwonLee** [comment]
Thank you for the quick reply! After the update, it is solved :)
